### ISSUE TITLE
curl里面的参数一直提示报错，是哪里没有配好吗

### ISSUE THREAD

**Issue by 9streets** [cnlyzy/sogou_wechat_spider#2]
[8] ErrorException in Index.php line 70
Use of undefined constant CURLOPT_SSL_VERIFYPEER - assumed 'CURLOPT_SSL_VERIFYPEER'
                $c_page = $page + $i;
                $urls[] = "http://weixin.sogou.com/weixin?query={$sogo_query}&_sug_type_=&s_from=input&_sug_=n&type=1&page={$c_page}&ie=utf8";
            }

            $cookie = cache('sogou_Cookie');
            QueryList::run('Multi', [
                'list' => $urls,
                'curl' => [
                    'opt' => array(
                        CURLOPT_SSL_VERIFYPEER => false,
                        CURLOPT_SSL_VERIFYHOST => false,
                        CURLOPT_FOLLOWLOCATION => true,
                        CURLOPT_AUTOREFERER => true,
                        CURLOPT_TIMEOUT => 10,
                        CURLOPT_PROXYTYPE => CURLPROXY_HTTP,
                        CURLOPT_PROXY => Config::get('proxy.PROXY_URL'),
                        CURLOPT_PROXYAUTH => CURLAUTH_BASIC,
                        CURLOPT_PROXYUSERPWD => Config::get('proxy.PROXY_USERPWD'),
                        CURLOPT_USERAGENT => $this->UA(),

**Comment by cnlyzy** [comment]
确保已经安装了 php-curl扩展？
